services:
  # PHP + Yii 1.1
  app:
    user: root
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: power_graph_app
    environment:
      API_LOGIN: ${API_LOGIN}
      API_PASSWORD: ${API_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - ./src:/var/www/html
      - vendor:/var/www/html/vendor
      - assets_volume:/var/www/html/assets
      - runtime_volume:/var/www/html/protected/runtime
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - power_graph_network
    # Команда для выдачи прав assets и runtime
    command: ["bash", "-c", "chown -R www-data:www-data /var/www/html/assets /var/www/html/protected/runtime && chmod -R 775 /var/www/html/assets /var/www/html/protected/runtime && cron && php-fpm"]
  # Nginx
  web:
    image: nginx:alpine
    container_name: power_graph_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:Z
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:Z
    depends_on:
      - app
    networks:
      - power_graph_network
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: power_graph_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_DEFAULT_PASSWORD}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - power_graph_network
  # MySQL
  db:
    image: mysql:5.7
    container_name: power_graph_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${DB_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    ports:
      - '3306:3306'
    expose:
        - '3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - power_graph_network

# Глобальные тома
volumes:
  db_data:
  rabbitmq_data:
  vendor:
  assets_volume:
  runtime_volume:

# Сети
networks:
  power_graph_network:
    driver: bridge