services:
  # PHP and Yii 1.1
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: power_graph_app
    volumes:
      - ./src:/var/www/html
      - vendor:/var/www/html/vendor
    depends_on:
      - db
      - rabbitmq
    networks:
      - power_graph_network
    command: ["bash", "-c", "chown -R www-data:www-data /var/www/html/assets /var/www/html/protected/runtime && chmod -R 775 /var/www/html/assets /var/www/html/protected/runtime && cron && php-fpm"]
    tty: true

  # Nginx
  web:
    image: nginx:alpine
    container_name: power_graph_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - power_graph_network

  # MySQL
  db:
    image: mysql:5.7
    container_name: power_graph_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: power_graph_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - power_graph_network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: power_graph_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user_password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - power_graph_network

# Глобальные тома
volumes:
  db_data:
  rabbitmq_data:
  vendor:

# Сети
networks:
  power_graph_network:
    driver: bridge